#!/usr/bin/env bash

function link() {
	if [[ ! -L "${2}" || "$(readlink "${2}")" != "${1}" ]]; then
		rm -rf "${2}"
		ln -sv "${1}" "${2}"
	fi
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

OS="$(uname)"
if [[ "${OS}" == "Linux" ]]; then
	sudo apt update
	sudo apt -y upgrade
	sudo apt -y install build-essential curl file git libreadline-dev procps
fi

SSH_TYPE="ed25519"
SSH_FILENAME="${HOME}/.ssh/id_${SSH_TYPE}"
if [[ ! -f "${SSH_FILENAME}" ]]; then
	ssh-keygen -t "${SSH_TYPE}" -N "" -f "${SSH_FILENAME}" -C "$(hostname)"
fi

PATH="/opt/homebrew/bin:/home/linuxbrew/.linuxbrew/bin:${PATH}"
if [[ -z "$(command -v brew)" ]]; then
	NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

eval "$(brew shellenv)"
brew bundle --file="${SCRIPT_DIR}/Brewfile"

mkdir -p ${HOME}/.{config,private}

# GIT
if [[ ! -f "${HOME}/.private/gitconfig" ]]; then
	read -p "Enter you name: " NAME
	read -p "Enter your email: " EMAIL
	cat <<_git_user >${HOME}/.private/gitconfig
[user]
	email = ${EMAIL}
	name = ${NAME}
_git_user
fi
link ${SCRIPT_DIR}/git/gitconfig ${HOME}/.gitconfig

# ZSH
mkdir -p ${HOME}/.config/fsh
link ${SCRIPT_DIR}/zsh/zshenv ${HOME}/.zshenv
link ${SCRIPT_DIR}/zsh/zshrc ${HOME}/.zshrc
link ${SCRIPT_DIR}/zsh/catppuccin-mocha.ini ${HOME}/.config/fsh/catppuccin-mocha.ini

link ${SCRIPT_DIR}/nvim ${HOME}/.config/nvim
link ${SCRIPT_DIR}/wezterm/wezterm.lua ${HOME}/.wezterm.lua

if [[ ! -f "${HOME}/.private/bugwarrior.toml" ]]; then
	cp ${SCRIPT_DIR}/task/bugwarrior.toml ${HOME}/.private/
fi

bat cache --build
# TODO: execute
# fast-theme XGD:catppuccin-mocha
