#!/usr/bin/env bash

link() {
	rm -rf "${2}"
	ln -sv "${1}" "${2}"
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

source ${SCRIPT_DIR}/environment

mkdir -p ${HOME}/.private
mkdir -p ${HOME}/.config

# GIT
touch ${HOME}/.private/gitconfig
link ${DOTFILES}/git/gitconfig ${HOME}/.gitconfig

# ZSH
link ${DOTFILES}/environment ${HOME}/.zshenv
link ${DOTFILES}/zsh/zimrc ${HOME}/.zimrc
link ${DOTFILES}/zsh/zshrc ${HOME}/.zshrc

link ${DOTFILES}/bat ${HOME}/.config/bat
link ${DOTFILES}/kitty ${HOME}/.config/kitty
link ${DOTFILES}/nvim ${HOME}/.config/nvim

# Install Homebrew
# TODO: skip prompt
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
eval "$(/opt/homebrew/bin/brew shellenv)"

# TODO: brew install

bat cache --build

# TODO: ssh-keygen -t ed25519 -C ""
# TODO: fast-theme ${DOTFILES}/zsh/catppuccin-mocha

# vim: noet ci pi sts=0 sw=4 ts=4
