#!/usr/bin/env bash

link() {
	rm -rf "${2}"
	ln -sv "${1}" "${2}"
}


SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

source ${SCRIPT_DIR}/environment
source ${SCRIPT_DIR}/software_mac

mkdir -p ${HOME}/.private

# GIT
touch ${HOME}/.private/gitconfig
link ${DOTFILES}/git/gitconfig ${HOME}/.gitconfig

# ZSH
link ${DOTFILES}/environment ${HOME}/.zshenv
link ${DOTFILES}/zsh/zshrc ${HOME}/.zshrc
link ${DOTFILES}/zsh/zimrc ${HOME}/.zimrc

# Kitty
link ${DOTFILES}/kitty ${HOME}/.config/kitty

# bat
link ${DOTFILES}/bat ${HOME}/.config/bat
bat cache --build

# nvim
rm -rf ~/.config/nvim ~/.local/share/nvim ~/.cache/nvim
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1 && nvim
link ${DOTFILES}/nvim ${HOME}/.config/nvim/lua/custom


# vim: noet ci pi sts=0 sw=4 ts=4
