#!/usr/bin/env bash

brew update

brew install asdf
brew install bash
brew install bat
brew install direnv
brew install fzf
brew install gnu-sed
brew install jq
brew install neovim
brew install ripgrep
brew install tree
brew install zoxide
brew install zsh
