#!/usr/bin/env bash

brew update

brew install asdf
brew install bash
brew install bat
brew install direnv
brew install fzf
brew install git-delta
brew install gnu-sed
brew install jq
brew install mike-engel/jwt-cli/jwt-cli
brew install neovim
brew install ripgrep
brew install tree
brew install tree-sitter
brew install zoxide
brew install zsh
