worktree-path = "{{ repo_path }}/../_wts/{{ branch | sanitize }}/{{ repo }}"

[pre-start]
setup = "npm ci"

[post-start]
copy = "wt step copy-ignored"

[step.copy-ignored]
exclude = ["build/", "coverage/", "dist/"]

[pre-remove]
protect-dev = """
if [[ {{ branch }} = poc/am-development ]]; then
	echo "Branch 'poc/am-development' is protected - removal blocked"
	exit 1
fi
"""
