worktree-path = "{{ repo_path }}/../{{ branch | sanitize }}"

[pre-remove]
protect-dev = """
if [[ {{ branch }} = poc/am-development ]]; then
	echo "Branch 'poc/am-development' is protected - removal blocked"
	exit 1
fi
"""
