auto_update = true
cbhist = true
clipboard_hotkey = "SUPER+SHIFT+C"
debounce_delay = 300
event_duration = 60
haptic_feedback = false
log_path = "/tmp/rustcast.log"
main_page = "blank"
placeholder = "Time to be productive!"
search_dirs = ["~"]
search_url = "https://duckduckgo.com/search?q=%s"
shells = []
show_trayicon = true
start_at_login = true
toggle_hotkey = "ALT+SPACE"

[buffer_rules]
clear_on_enter = true
clear_on_hide = true

[theme]
background_color = [0.118, 0.118, 0.180]	# Mocha Base #1E1E2E
background_opacity = 1.0
blur = false
show_icons = true
show_scroll_bar = false
text_color = [0.804, 0.839, 0.957]			# Mocha Text #CDD6F4

[modes]

[aliases]
